### ISSUE TITLE
Reconnection problem - cannot rerun script 

### ISSUE THREAD

**Issue by pagf-git** [lionel-rigoux/vernier-toolbox#1]
I am using the vernier hand dynamometer with the minimal script ('dynamometer_example.m').

The script runs well the first time I start Matlab and plug in the dynamometer. However, when I rerun the same script, I get the following error:

GoIO lib version 2.41 loaded.
Found 1 GoLink(s)
Error using dynamometer/connect_sensor (line 297)
*** Cannot connect to sensor 1.

Error in dynamometer/open (line 368)
               dy.connect_sensor(sensor_num) ;

Error in dynamometer (line 414)
           dy = dy.open(sensor_num);

Error in dynamometer_example (line 16)
d=dynamometer;

I have done some investigating and it seems as soon as I run 'd.stop', Matlab disconnects the dynamometer so if I try to rerun the script (i.e. 'd.start'), it cannot connect to it. This means I need to manually disconnect and reconnect the dynamometer and restart matlab each time I want to rerun the script (I am using Windows 10 and Matlab 2017b).

It does not seem to be a problem with the device. For example, if I open LoggerLite (the software that comes with the dynamometer), this program can find the dynamometer and connect to it (even though Matlab can't).

I was wondering if you had encountered this problem before or if you know a way to solve it.

For example, is there a way to get Matlab to disconnect and reconnect to the device without having to do it manually?

Any guidance or advice would be very much appreciated. Thanks!

**Comment by helenahartmann** [comment]
What I found out is that if you "clear all" (or at least clear everything besides some relevant variables you might want to keep) after having used the dynamometer in a script, you can restart a new script using it without having to close matlab. apparently it deletes all relevant objects related to the dynamometer! however, I still have to replug the device for it to work...

**Comment by lionel-rigoux** [comment]
Should be solved in the new version.
